# Generated by Django 5.1.1 on 2024-09-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_image/')),
                ('course_name', models.CharField(choices=[('WEB', 'Web Developer'), ('MLE', 'Machine Learning Engineer'), ('DS', 'Data Scientist'), ('DBA', 'Database Administrator'), ('SE', 'Software Engineer'), ('UX', 'UX/UI Designer'), ('PM', 'Product Manager'), ('QA', 'Quality Assurance Engineer'), ('CS', 'Cyber Security Specialist'), ('AI', 'AI Researcher'), ('CLOUD', 'Cloud Architect'), ('BI', 'Business Intelligence Analyst'), ('DEVOPS', 'DevOps Engineer'), ('FRONTEND', 'Frontend Developer'), ('BACKEND', 'Backend Developer')], default='UX', max_length=25)),
                ('course_code', models.CharField(max_length=13, unique=True)),
                ('start_class', models.DateField(blank=True, null=True)),
                ('course_time', models.TimeField(blank=True, null=True)),
                ('course_length', models.CharField(blank=True, max_length=8, null=True)),
                ('total_sit', models.IntegerField(blank=True, null=True)),
                ('course_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
