# Generated by Django 5.1.1 on 2024-09-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_image/')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('education', models.CharField(choices=[('PSC', 'Primary School Certificate'), ('JSC', 'Junior School Certificate'), ('SSC', 'Secondary School Certificate'), ('HSC', 'Higher Secondary Certificate'), ('DIP', 'Diploma in Engineering'), ('BSC', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('BBA', 'Bachelor of Business Administration'), ('MSC', 'Master of Science'), ('MA', 'Master of Arts'), ('MBA', 'Master of Business Administration'), ('PHD', 'Doctor of Philosophy')], default='SSC', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('membership_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('user_type', models.CharField(choices=[('MEM', 'Member'), ('CCN', 'Course Coordinator'), ('ADM', 'Admin')], default='MEM', max_length=8)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
