# Generated by Django 5.1.1 on 2024-09-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('instractor_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('excluci', models.CharField(choices=[('CCO', 'Chief Compliance Officer'), ('CPO', 'Chief Product Officer'), ('COO', 'Chief Operating Officer'), ('CEO', 'Chief Executive Officer'), ('CFO', 'Chief Financial Officer'), ('CTO', 'Chief Technology Officer'), ('CIO', 'Chief Information Officer'), ('CMO', 'Chief Marketing Officer'), ('CSO', 'Chief Security Officer'), ('CHRO', 'Chief Human Resources Officer'), ('CAO', 'Chief Analytics Officer'), ('CDAO', 'Chief Data and Analytics Officer'), ('CISO', 'Chief Information Security Officer'), ('CGO', 'Chief Growth Officer')], default='CCO', max_length=20)),
                ('education', models.CharField(choices=[('PSC', 'Primary School Certificate'), ('JSC', 'Junior School Certificate'), ('SSC', 'Secondary School Certificate'), ('HSC', 'Higher Secondary Certificate'), ('DIP', 'Diploma in Engineering'), ('BSC', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('BBA', 'Bachelor of Business Administration'), ('MSC', 'Master of Science'), ('MA', 'Master of Arts'), ('MBA', 'Master of Business Administration'), ('PHD', 'Doctor of Philosophy')], default='SSC', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('country', models.CharField(choices=[('SL', 'Select Country Name'), ('BD', 'Bangladesh'), ('IN', 'India'), ('US', 'United States'), ('CA', 'Canada'), ('AU', 'Australia'), ('GB', 'United Kingdom'), ('CN', 'China'), ('JP', 'Japan'), ('DE', 'Germany'), ('FR', 'France'), ('ZA', 'South Africa'), ('RU', 'Russia'), ('MX', 'Mexico'), ('IT', 'Italy'), ('ES', 'Spain'), ('NG', 'Nigeria'), ('AR', 'Argentina'), ('SA', 'Saudi Arabia'), ('KR', 'South Korea'), ('ID', 'Indonesia'), ('TR', 'Turkey'), ('EG', 'Egypt'), ('PK', 'Pakistan'), ('NL', 'Netherlands'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('BE', 'Belgium'), ('PL', 'Poland'), ('MY', 'Malaysia'), ('PH', 'Philippines'), ('TH', 'Thailand'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('VN', 'Vietnam'), ('IL', 'Israel'), ('NO', 'Norway'), ('FI', 'Finland'), ('NZ', 'New Zealand'), ('SG', 'Singapore'), ('AE', 'United Arab Emirates'), ('GR', 'Greece'), ('PT', 'Portugal'), ('CZ', 'Czech Republic'), ('HU', 'Hungary'), ('AT', 'Austria'), ('DK', 'Denmark'), ('IE', 'Ireland'), ('CL', 'Chile'), ('RO', 'Romania'), ('KE', 'Kenya')], default='SL', max_length=20)),
                ('possiton', models.CharField(choices=[('WEB', 'Web Developer'), ('MLE', 'Machine Learning Engineer'), ('DS', 'Data Scientist'), ('DBA', 'Database Administrator'), ('SE', 'Software Engineer'), ('UX', 'UX/UI Designer'), ('PM', 'Product Manager'), ('QA', 'Quality Assurance Engineer'), ('CS', 'Cyber Security Specialist'), ('AI', 'AI Researcher'), ('CLOUD', 'Cloud Architect'), ('BI', 'Business Intelligence Analyst'), ('DEVOPS', 'DevOps Engineer'), ('FRONTEND', 'Frontend Developer'), ('BACKEND', 'Backend Developer')], default='DS', max_length=20)),
                ('linkdlen_id', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_image/')),
            ],
        ),
    ]
