# Generated by Django 5.1.1 on 2024-09-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_remove_instractor_add_instractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instractor',
            name='instractor_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
