# Generated by Django 5.1.1 on 2024-09-26 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_course', '0001_initial'),
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Nogod', 'Nogod'), ('Bkash', 'Bkash'), ('Rocket', 'Rocket'), ('Visa', 'Visa Card'), ('Paypal', 'Paypal')], max_length=10, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('course_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.course_module')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_course.course')),
                ('enroll_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
